A=int(10)
B=str("Devansh Rawat")
C=float(20.6)
D=list(("Apple","Orange","Banana"))
E=tuple(("Ostrich","Monkey","Zebra"))
F=range(2,10)
G=dict(name="Dev",age=22)
H=set(("Mango","Peach","tomato"))
I=frozenset(("Asian","Europian","African"))
J=bool(5)
K=bytes(5)
L=bytearray(5)
M=memoryview(bytes(5))
print([type(x) for x in (A, B, C, D, E, F, G, H, I, J, K, L, M)])
for item in (A, B, C, D, E, F, G, H, I, J, K, L, M):
    print(type(item))